-- DROP TABLES SI EXISTEN
DROP TABLE IF EXISTS historial_estados CASCADE;
DROP TABLE IF EXISTS pedido_productos CASCADE;
DROP TABLE IF EXISTS pedidos CASCADE;
DROP TABLE IF EXISTS empleados CASCADE;
DROP TABLE IF EXISTS estados CASCADE;
DROP TABLE IF EXISTS productos CASCADE;
DROP TABLE IF EXISTS clientes CASCADE;

-- CREACIÓN DE TABLAS

-- Tabla Clientes
CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_completo TEXT NOT NULL,
  telefono TEXT NOT NULL,
  email TEXT NOT NULL,
  direccion TEXT
);

-- Tabla Productos
CREATE TABLE productos (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   nombre TEXT NOT NULL,
   descripcion TEXT,
   precio_base NUMERIC(10,2) NOT NULL,
   disponibilidad BOOLEAN NOT NULL
);

-- Tabla Estados
CREATE TABLE estados (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nombre TEXT NOT NULL
);

-- Tabla Empleados
CREATE TABLE empleados (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   nombre TEXT NOT NULL,
   rol TEXT NOT NULL,
   especialidad TEXT
);

-- Tabla Pedidos
CREATE TABLE pedidos (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 cliente_id BIGINT NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
 fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 fecha_entrega_estimada TIMESTAMP NOT NULL,
 estado_actual_id BIGINT NOT NULL REFERENCES estados(id),
 total_pagar NUMERIC(10,2) NOT NULL
);

-- Tabla Pedido_Productos
CREATE TABLE pedido_productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL REFERENCES pedidos(id) ON DELETE CASCADE,
  producto_id BIGINT NOT NULL REFERENCES productos(id),
  cantidad INTEGER NOT NULL,
  personalizacion TEXT,
  precio_final NUMERIC(10,2) NOT NULL
);

-- Tabla Historial_Estados
CREATE TABLE historial_estados (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   empleado_id BIGINT NOT NULL REFERENCES empleados(id),
   pedido_id BIGINT NOT NULL REFERENCES pedidos(id),
   estado_id BIGINT NOT NULL REFERENCES estados(id),
   fecha_cambio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   comentario TEXT
);